PS-4289: PXC 5.7.43 refresh - Q3 2023 (Fix gcc-13 errors)
https://jira.percona.com/browse/PXC-4289

Description
-----------
Server compilation fails with gcc-13 due to nonnull-compare of `this`
pointer in the WSREP(THD) macro.

  sql/sql_class.h: In member function ‘void THD::set_query_id(query_id_t, bool)’:
  sql/sql_class.h:5196:9: error: ‘nonnull’ argument ‘this’ compared to NULL [-Werror=nonnull-compare]

We get this error when `this` pointer is compared with NULL when
Werror=nonnull-compare is specified.

Solution
--------
Occurences of `WSREP(this)` have been replaced with `WSREP_NNULL(this)`.